compare/comparisons/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='comparisons/home.html'), name="home"),
    url(
        regex=r'^compare/(?P<pk>[\d]+)/$',
        view=views.ComparisonPlatformView.as_view(),
        name='platform'
    ),
    url(
        regex=r'^browse/$',
        view=views.ComparisonListView.as_view(),
        name='browse'
    ),
    url(
        regex=r'^create/$',
        view=views.ComparisonCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[\d]+)/$',
        view=views.ComparisonDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>[\d]+)/update/$',
        view=views.ComparisonUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^submit/(?P<pk>[\d]+)/$',
        view=views.ComparisonItemCreateView.as_view(),
        name='submit'
    ),
]

compare/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name="contact"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("compare.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^comparisons/', include("compare.comparisons.urls", namespace="comparisons"))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page Not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

compare/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from django_countries.fields import CountryField


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("What's your name?"), blank=True, max_length=255)
    about = models.TextField(_("A little something about yourself?"), blank=True)
    country = CountryField(_("Where do you live?"), blank=True, blank_label='<pick one>')

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

compare/comparisons/forms.py
from django import forms
from django.utils import timezone

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, ButtonHolder, Submit, HTML


class ComparisonCreateForm(forms.Form):
    title = forms.CharField(required=True, label="What should it be called?")
    description = forms.CharField(required=False, widget=forms.Textarea, label="Outline the rules, guidelines, and anything else important about this comparison.")
    date_starting = forms.DateField(required=True, label="When should we start?", initial=timezone.now().strftime("%m/%d/%Y"))
    date_ending = forms.DateField(required=False, label="When should we finish?")

    def __init__(self, *args, **kwargs):
        super(ComparisonCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_action = 'comparisons:create'
        self.helper.layout = Layout(
            Fieldset(
                None,
                'title',
                'description',
                Field('date_starting', css_class="date-picker", placeholder="Pick a start date"),
                Field('date_ending', css_class="date-picker", placeholder="Pick an end date (optional)"),
            )
        )
        self.helper.add_input(Submit('submit', 'Submit'))


class ComparisonUpdateForm(forms.Form):
    title = forms.CharField(required=True, label="What should it be called?")
    description = forms.CharField(required=False, widget=forms.Textarea, label="Outline the rules, guidelines, and anything else important about this comparison.")
    date_starting = forms.DateField(required=True, label="When should we start?")
    date_ending = forms.DateField(required=False, label="When should we finish?")

    def __init__(self, *args, **kwargs):
        super(ComparisonUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                None,
                'title',
                'description',
                Field('date_starting', css_class="date-picker", placeholder="Pick a start date"),
                Field('date_ending', css_class="date-picker", placeholder="Pick an end date (optional)"),
            )
        )
        self.helper.add_input(Submit('submit', 'Update'))


class ComparisonItemCreateForm(forms.Form):
    title = forms.CharField(required=False, label="Give it a name.")
    description = forms.CharField(required=False, widget=forms.Textarea, label="Give a brief description.")
    image = forms.ImageField(required=True, label="Choose an image to submit. You can preview it before submitting.")

    def __init__(self, *args, **kwargs):
        super(ComparisonItemCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                None,
                'title',
                'description',
                'image',
                HTML("""<div class="image_preview m-b-1"><img id='image_preview'/></div>""")
            )
        )
        self.helper.add_input(Submit('submit', 'Submit'))

compare/comparisons/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from datetime import date

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, TemplateView
from django.core.exceptions import PermissionDenied

from braces.views import LoginRequiredMixin

from .models import Comparison, ComparisonItem
from .forms import ComparisonCreateForm, ComparisonUpdateForm, ComparisonItemCreateForm
from compare.users.models import User


class ComparisonCreateView(LoginRequiredMixin, CreateView):
    template_name = "comparisons/comparison_form.html"
    fields = ['title', 'description', 'date_starting', 'date_ending',]
    model = Comparison

    def form_valid(self, form):
        owner = self.request.user
        form.instance.owner = owner
        return super(ComparisonCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ComparisonCreateView, self).get_context_data(**kwargs)
        context['comparison_create_form'] = ComparisonCreateForm()
        return context


class ComparisonUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "comparisons/comparison_update.html"
    fields = ['title', 'description', 'date_starting', 'date_ending',]
    model = Comparison

    # Users should only be able to update their own comparisons. Handled here.
    def dispatch(self, request, *args, **kwargs):
        if request.user.username != self.get_object().owner.username:
            messages.error(request, "This doesn't belong to you, so you can't edit it!")
            return redirect(reverse('comparisons:detail', kwargs={'pk': self.kwargs['pk']}))
        return super(ComparisonUpdateView, self).dispatch(request, *args, **kwargs)

    # Handles the prepopulation of the form (since there's already stuff there)
    def get_context_data(self, **kwargs):
        context = super(ComparisonUpdateView, self).get_context_data(**kwargs)
        instance = self.get_object()

        # This is ugly; let's change the model at some point to make this required or default to something.
        if instance.date_ending:
            date_ending = instance.date_ending.strftime("%m/%d/%Y")
        else:
            date_ending = None

        initial = {'title': instance.title,
                'description': instance.description,
                'date_starting': instance.date_starting.strftime("%m/%d/%Y"),
                'date_ending': date_ending}
        comparison_update_form = ComparisonUpdateForm(initial=initial)
        comparison_update_form.helper.form_action = reverse("comparisons:update", kwargs={'pk': instance.pk})
        context['comparison_update_form'] = comparison_update_form
        return context

    def form_valid(self, form):
        if form.instance.owner.username != request.user.username:
            messages.error("This doesn't belong to you, so you can't edit it!")
            return redirect(reverse('comparisons:detail', kwargs={'pk': self.kwargs['pk']}))
        return super(ComparisonUpdateView, self).form_valid(form)


class ComparisonDetailView(LoginRequiredMixin, DetailView):
    template_name = "comparisons/comparison_detail.html"
    model = Comparison
    slug_field = "pk"
    slug_url_kwarg = "pk"

    # Overriding the method to return related comparisonitems sorted by score
    def get_context_data(self, **kwargs):
        context = super(ComparisonDetailView, self).get_context_data(**kwargs)
        context['current_day'] = date.today()
        context['related_comparisonitems'] = ComparisonItem.objects.filter(comparison__exact = self.get_object()).order_by('-score')
        return context


# This view returns the full list of comparisons if there's no ?username token.
# If there is a ?username token it'll return all of that user's comparisons.
class ComparisonListView(ListView):
    template_name = "comparisons/comparison_list.html"
    model = Comparison

    # This handles the filtering on the username
    def get_queryset(self):
        username = self.request.GET.get('username')
        if username == None:
            return super(ComparisonListView, self).get_queryset()
        self.user = get_object_or_404(User, username=username)
        return Comparison.objects.filter(owner=self.user)

    # Passes down different context depending on the token existence.
    def get_context_data(self, **kwargs):
        context = super(ComparisonListView, self).get_context_data(**kwargs)
        username = self.request.GET.get('username')
        if username == None:
            context['title'] = "All Comparisons"
        else:
            context['title'] = username + "'s Comparisons"
        return context


class ComparisonItemCreateView(LoginRequiredMixin, CreateView):
    template_name = "comparisons/comparison_submit.html"
    model = ComparisonItem
    fields = ['title', 'description', 'image',]

    # Rather not let a user submit to a contest if it's already over. Raise a 403 instead.
    def dispatch(self, request, *args, **kwargs):
        comparison = get_object_or_404(Comparison, pk=self.kwargs['pk'])
        today = date.today()
        if (comparison.date_starting and today < comparison.date_starting) or (comparison.date_ending and today > comparison.date_ending):
            messages.error(request, "Sorry, you can't submit to a competition that's already ended!")
            return redirect(reverse('comparisons:detail', kwargs={'pk': self.kwargs['pk']}))
        return super(ComparisonItemCreateView, self).dispatch(request, *args, **kwargs)

    # After a successful submit, returns the user to that comparison's page
    def get_success_url(self):
        success_url =  reverse_lazy("comparisons:detail", kwargs={'pk': self.kwargs['pk']})
        return success_url

    def get_context_data(self, **kwargs):
        context = super(ComparisonItemCreateView, self).get_context_data(**kwargs)
        comparison_item_create_form = ComparisonItemCreateForm()
        comparison_item_create_form.helper.form_action = reverse("comparisons:submit", kwargs={'pk': self.kwargs['pk']})
        pk = self.kwargs['pk'] # pk of the parent comparison!
        context['comparison'] = get_object_or_404(Comparison, pk=pk)
        context['comparison_item_create_form'] = comparison_item_create_form
        return context

    def form_valid(self, form):
        owner = self.request.user
        pk = self.kwargs['pk']
        comparison = get_object_or_404(Comparison, pk=pk)
        form.instance.owner = owner
        form.instance.comparison = comparison
        messages.success(self.request, "Your submission has been accepted!")
        return super(ComparisonItemCreateView, self).form_valid(form)


class ComparisonPlatformView(LoginRequiredMixin, TemplateView):
    template_name = "comparisons/comparison_platform.html"

    def get_context_data(self, **kwargs):
        context = super(ComparisonPlatformView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['comparison'] = get_object_or_404(Comparison, pk=pk)
        return context

compare/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'about', 'country',]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

compare/templates/comparisons/comparison_detail.html
{% extends "base.html" %}
{% load static thumbnail humanize %}

{% block content %}

<h1 style="display: inline;">{{ object.title }} </h1>{% if object.owner == request.user %}<p style="display: inline;">(<a href="{% url 'comparisons:update' object.pk %}">Edit</a>)</p>{% endif %}
<p class="font-italic">A comparison set created by {{ object.owner.username }}. So far, {{ related_comparisonitems.count }} submissions have been made.</p>

<div class="card card-block row">
  {% if object.description %}
  <h4>Description</h4>
  <p>{{ object.description }}</p>
  {% endif %}

  <p>Created <span class="font-weight-bold">{{ object.date_created|naturalday:"F j, o" }}</span>.</p>

  {% if object.date_starting %}
  <p>{% if object.date_starting <= current_day %}Started{% else %}Starting{% endif %} <span class="font-weight-bold">{{ object.date_starting|naturalday:"F j, o" }}</span>.</p>
  {% endif %}

  {% if object.date_ending %}
  <p>{% if object.date_ending <= current_day %}Ended{% else %}Ending{% endif %} <span class="font-weight-bold">{{ object.date_ending|naturalday:"F j, o" }}</span>.</p>
  {% endif %}

  <div><h4 style="display: inline;">Submissions </h4><a href="{% url 'comparisons:submit' object.pk %}" class="make-submission-icon" title="Make a submission"><i style="display: inline;" class="fa fa-plus fa-lg"></i></a></div>
  {% if related_comparisonitems %}
  {% for comparisonitem in related_comparisonitems %}
  {% thumbnail comparisonitem.image "200x200" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" {% if comparisonitem.title %}data-toggle="tooltip" data-placement="top" title="'{{ comparisonitem.title }}', by {{ comparisonitem.owner.username }}"{% else %}data-toggle="tooltip" data-placement="top" title="Submission by {{ comparisonitem.owner.username }}"{% endif %}>
  {% endthumbnail %}
  {% endfor %}
  {% else %}
  <p>It looks like nobody's submitted anything here. <a href="{% url 'comparisons:submit' object.pk %}">You can be the first!</a></p>
  {% endif %}

{% endblock content %}

compare/templates/comparisons/comparison_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Create Comparison</h1>
<div class="card card-block row">
  <h3 class="card-title">Create Comparison</h1>
  {% crispy comparison_create_form %}
</div>
{% endblock %}

compare/templates/comparisons/comparison_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}

{% block content %}

<div class="container">

    <h2>{{ title }}</h2>

    <div class="list-group">
        {% if object_list %}
        {% for comparison in object_list %}
          <a href="{% url 'comparisons:detail' comparison.pk %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ comparison.title }}</h4>
          </a>
        {% endfor %}
        {% else %}
        <p>There doesn't seem to be anything here. That's a little sad. Maybe you should <a href="{% url 'comparisons:create' %}">create a competition</a>!
        {% endif %}
    </div>

{% endblock content %}

compare/templates/comparisons/comparison_platform.html
{% extends "base.html" %}

{% block content %}

{{ comparison }} <!--Get rid of this when the time comes! -->



{% endblock %}

compare/templates/comparisons/comparison_submit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Submit Comparison</h1>
<div class="card card-block row">
  <h3 class="card-title">Make a Submission to "{{ comparison.title }}"</h1>
  {% crispy comparison_item_create_form %}

</div>
{% if comparison_item_create_form.image.value %}<script>alert("hello!")</script>{% endif %}
<script>
  function upload_img(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#image_preview').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
      $("#image_preview").attr("width", "300");
    }
  }
  $(document).ready(function() {
    $("#id_image").wrap("<span class='btn btn-primary btn-file'>Browse</span>");
    $("#id_image").attr("onchange", "upload_img(this);");
  });
</script>
{% endblock %}

compare/templates/comparisons/comparison_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Update Comparison</h1>
<div class="card card-block row">
  <h3 class="card-title">Change Comparison</h1>
  {% crispy comparison_update_form %}
</div>
{% endblock %}

compare/templates/comparisons/home.html
{% extends "base.html" %}

{% block content %}

<h1>Comparisons</h1>
<p>It's not a competition. Just kidding. It's <em>absolutely</em> a competition.</p>
<div class="row">
  <div class="col-sm-4 card card-block">
    <h3 class="card-title">Browse</h3>
    <p class="card-text">See active comparisons, make a submission, have your voice heard.</p>
    <a href="{% url 'comparisons:browse' %}" class="btn btn-primary">Browse</a>
  </div>
  <div class="col-sm-4 card card-block">
    <h3 class="card-title">Create</h3>
    <p class="card-text">Create your own comparisons, see where everything stacks up.</p>
    <a href="{% url 'comparisons:create' %}" class="btn btn-primary">Create</a>
  </div>
  {% if request.user.is_authenticated %}
  <div class="col-sm-4 card card-block">
    <h3 class="card-title">Manage</h3>
    <p class="card-text">View and modify your competitions, visualize the rankings.</p>
    <a href="{% url 'comparisons:browse' %}?username={{ request.user.username }}" class="btn btn-primary">Manage</a>
  </div>
  {% endif %}
</div>

{% endblock %}